### EDA: https://catalogo.datos.gba.gob.ar/sv/dataset/establecimientos-educativos?

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
ruta = "../data/raw/establecimientos_educativos.csv"
df_establecimientos = pd.read_csv(ruta)

df_establecimientos.head()

,municipio_id,municipio_nombre,establecimiento_id,establecimiento_nombre,region_educativa,clave,cueanexo,modalidad,nivel,direccion,...,matricula,varones,mujeres,secciones,turnos,cue,anexo,nro_escuela,latitud,longitud
0,6441,La Plata,1,ESCUELA DE DANZAS CLASICAS Nº3,Región 1,0001AD0003,61060000,Educación Artística,Nivel Superior,54 E/ 7 Y 8 - 628,...,205.0,8.0,197.0,20.0,"MAÑANA,TARDE,VESPERTINO",610600.0,0.0,3.0,-34.917432,-57.947606
1,6441,La Plata,1,ESCUELA DE DANZAS CLASICAS Nº3,Región 1,0001AD0003,61060000,Educación Artística,Ciclo Medio,54 E/ 7 Y 8 - 628,...,230.0,15.0,215.0,15.0,"MAÑANA,TARDE,VESPERTINO",610600.0,0.0,3.0,-34.917432,-57.947606
2,6441,La Plata,1,ESCUELA DE DANZAS CLASICAS Nº3,Región 1,0001AD0003,61060000,Educación Artística,Ciclo de Iniciación,54 E/ 7 Y 8 - 628,...,180.0,1.0,179.0,14.0,"MAÑANA,TARDE,VESPERTINO",610600.0,0.0,3.0,-34.917432,-57.947606
3,6441,La Plata,2,"ESCUELA DE EDUCACIÓN ARTÍSTICA Nº1 ""MARÍA INÉS...",Región 1,0001AE0001,61498400,Educación Artística,Cursos y Talleres,45 - 743,...,1455.0,624.0,831.0,72.0,"MAÑANA,TARDE,VESPERTINO",614984.0,0.0,1.0,-34.914041,-57.957036
4,6441,La Plata,3,ESCUELA DE EDUCACIÓN ARTÍSTICA Nº2,Región 1,0001AE0002,61498500,Educación Artística,Cursos y Talleres,76 - RELOCALIZADOS EN EL ISFDYT N° 12 - S/N,...,916.0,424.0,492.0,49.0,"MAÑANA,TARDE,VESPERTINO",614985.0,0.0,2.0,-34.934052,-57.924258

In [3]:
df_establecimientos.shape

(490, 35)

In [4]:
df_establecimientos.info()

<class 'pandas.DataFrame'>
RangeIndex: 490 entries, 0 to 489
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   municipio_id            490 non-null    int64
 1   municipio_nombre        490 non-null    str
 2   establecimiento_id      490 non-null    int64
 3   establecimiento_nombre  490 non-null    str
 4   region_educativa        490 non-null    str
 5   clave                   490 non-null    str
 6   cueanexo                490 non-null    int64
 7   modalidad               490 non-null    str
 8   nivel                   490 non-null    str
 9   direccion               489 non-null    str
 10  telefono                489 non-null    str
 11  rpv                     296 non-null    str
 12  email                   488 non-null    str
 13  sector                  489 non-null    str
 14  dependencia             489 non-null    str
 15  tipo_organizacion       489 non-null    str
 16  area                    489 non-null    str
 17  ambito                  489 non-null    str
 18  desfavorabilidad        489 non-null    float64
 19  subvencion              489 non-null    str
 20  sede_axo_ext            489 non-null    str
 21  categoria               489 non-null    str
 22  depend_func             489 non-null    str
 23  cui                     489 non-null    str
 24  periodo                 489 non-null    str
 25  matricula               489 non-null    float64
 26  varones                 489 non-null    float64
 27  mujeres                 489 non-null    float64
 28  secciones               489 non-null    float64
 29  turnos                  484 non-null    str
 30  cue                     489 non-null    float64
 31  anexo                   489 non-null    float64
 32  nro_escuela             489 non-null    float64
 33  latitud                 489 non-null    float64
 34  longitud                489 non-null    float64
dtypes: float64(10), int64(3), str(22)
memory usage: 134.1 KB

In [5]:
df_establecimientos.columns.tolist()

['municipio_id',
 'municipio_nombre',
 'establecimiento_id',
 'establecimiento_nombre',
 'region_educativa',
 'clave',
 'cueanexo',
 'modalidad',
 'nivel',
 'direccion',
 'telefono',
 'rpv',
 'email',
 'sector',
 'dependencia',
 'tipo_organizacion',
 'area',
 'ambito',
 'desfavorabilidad',
 'subvencion',
 'sede_axo_ext',
 'categoria',
 'depend_func',
 'cui',
 'periodo',
 'matricula',
 'varones',
 'mujeres',
 'secciones',
 'turnos',
 'cue',
 'anexo',
 'nro_escuela',
 'latitud',
 'longitud']

In [6]:
#¿Qué años tiene el csv? "Período" describe el período o momento del Relevamiento de Datos
df_establecimientos["periodo"].value_counts()

periodo
Inicial 2026    489
Name: count, dtype: int64

In [7]:
#¿Qué regiones aparecen?
df_establecimientos["region_educativa"].value_counts()

region_educativa
Región 1     338
Región 5      80
Región 23     42
Región 15     29
Región 4       1
Name: count, dtype: int64

In [8]:
#¿Qué niveles aparecen?
df_establecimientos["nivel"].value_counts()

nivel
Nivel Primario                                       235
Nivel Inicial                                        123
Nivel Secundario                                      54
Formación Integral                                    33
Nivel Superior                                        14
Formación Profesional                                 10
Residencia Laboral,Pasantías, Artística                4
Educación Física (C.E.F.)                              4
Ciclo Medio                                            3
Ciclo de Iniciación                                    3
Cursos y Talleres                                      2
Plan Fines (Trayectos y Deudores)                      2
Psicología Comunitaria y Pedagogía Social (C.E.C)      2
Ni                                                     1
Name: count, dtype: int64

In [9]:
#¿Qué modalidades aparecen?
df_establecimientos["modalidad"].value_counts()

modalidad
Educación Común                              260
Educación de Jóvenes y Adultos                99
Educación Especial                            97
Educación Técnico Profesional                 16
Educación Artística                           12
Educación Física                               4
Psicología Comunitaria y Pedagogía Social      2
Name: count, dtype: int64

In [10]:
total_municipios = df_establecimientos["municipio_nombre"].nunique()
nombres = df_establecimientos["municipio_nombre"].unique().tolist()

print(f"La cantidad total de municipios que figuran es: {total_municipios}; los mismos son: {nombres}")

La cantidad total de municipios que figuran es: 6; los mismos son: ['La Plata', 'Florencio Varela', 'Berisso', 'Adolfo Alsina', 'Alberti', 'Almirante Brown']

In [11]:
df_establecimientos["municipio_nombre"].value_counts()

municipio_nombre
La Plata            337
Almirante Brown      80
Adolfo Alsina        42
Alberti              29
Florencio Varela      1
Berisso               1
Name: count, dtype: int64

In [12]:
df_establecimientos["establecimiento_id"].nunique()

417

In [13]:
establecimientos_por_municipio = (
    df_establecimientos
    .groupby("municipio_nombre")["establecimiento_id"]
    .nunique()
    .sort_values(ascending=False)
    
)

print(establecimientos_por_municipio)

municipio_nombre
La Plata            290
Almirante Brown      64
Adolfo Alsina        36
Alberti              25
Berisso               1
Florencio Varela      1
Name: establecimiento_id, dtype: int64

Como los establecimientos se repiten, entonces el mismo estableciemiento puede aparecer más de una vez dependiendo la cantidad de orientaciones que tiene el mismo.

In [14]:
df_establecimientos["establecimiento_id"].value_counts().head(10)

establecimiento_id
71     4
72     4
369    4
1      3
7      3
8      3
54     3
56     3
57     3
58     3
Name: count, dtype: int64

In [15]:
df_establecimientos[df_establecimientos["establecimiento_id"] == 71]

,municipio_id,municipio_nombre,establecimiento_id,establecimiento_nombre,region_educativa,clave,cueanexo,modalidad,nivel,direccion,...,matricula,varones,mujeres,secciones,turnos,cue,anexo,nro_escuela,latitud,longitud
97,6441,La Plata,71,"ESCUELA ESPECIAL Nº535 ""JUANA AZURDUY""",Región 1,0001EE0535,61138800,Educación Especial,Nivel Inicial,143 E/ 65 Y 66 - S/N,...,30.0,18.0,12.0,0.0,"MAÑANA,TARDE",611388.0,0.0,535.0,-34.959536,-57.972355
98,6441,La Plata,71,"ESCUELA ESPECIAL Nº535 ""JUANA AZURDUY""",Región 1,0001EE0535,61138800,Educación Especial,Nivel Primario,143 E/ 65 Y 66 - S/N,...,132.0,77.0,55.0,0.0,"MAÑANA,TARDE",611388.0,0.0,535.0,-34.959536,-57.972355
99,6441,La Plata,71,"ESCUELA ESPECIAL Nº535 ""JUANA AZURDUY""",Región 1,0001EE0535,61138800,Educación Especial,Formación Profesional,143 E/ 65 Y 66 - S/N,...,30.0,30.0,0.0,0.0,"MAÑANA,TARDE",611388.0,0.0,535.0,-34.959536,-57.972355
100,6441,La Plata,71,"ESCUELA ESPECIAL Nº535 ""JUANA AZURDUY""",Región 1,0001EE0535,61138800,Educación Especial,Formación Integral,143 E/ 65 Y 66 - S/N,...,153.0,87.0,66.0,0.0,"MAÑANA,TARDE",611388.0,0.0,535.0,-34.959536,-57.972355

In [16]:
len(df_establecimientos)

490

In [17]:
niveles_por_establecimiento = (
    df_establecimientos
    .groupby("establecimiento_id")["nivel"]
    .nunique()
)

print("Cantidad de establecimientos:", df_establecimientos["establecimiento_id"].nunique())
print("\nCantidad de establecimientos según número de niveles:")
print(niveles_por_establecimiento.value_counts().sort_index())

Cantidad de establecimientos: 417

Cantidad de establecimientos según número de niveles:
nivel
1    379
2      7
3     28
4      3
Name: count, dtype: int64

In [18]:
#Establecimientos por nivel
print("\nEstablecimientos por nivel:")
print(
    df_establecimientos
    .groupby("nivel")["establecimiento_id"]
    .nunique()
    .sort_values(ascending=False)
)

Establecimientos por nivel:
nivel
Nivel Primario                                       235
Nivel Inicial                                        123
Nivel Secundario                                      53
Formación Integral                                    33
Nivel Superior                                        14
Formación Profesional                                 10
Residencia Laboral,Pasantías, Artística                4
Educación Física (C.E.F.)                              4
Ciclo Medio                                            3
Ciclo de Iniciación                                    3
Cursos y Talleres                                      2
Plan Fines (Trayectos y Deudores)                      2
Psicología Comunitaria y Pedagogía Social (C.E.C)      2
Ni                                                     1
Name: establecimiento_id, dtype: int64

In [19]:
#¿Cuántos establecimientos ofrecen cada nivel?
df_establecimientos.groupby("nivel")["establecimiento_id"].nunique()

nivel
Ciclo Medio                                            3
Ciclo de Iniciación                                    3
Cursos y Talleres                                      2
Educación Física (C.E.F.)                              4
Formación Integral                                    33
Formación Profesional                                 10
Ni                                                     1
Nivel Inicial                                        123
Nivel Primario                                       235
Nivel Secundario                                      53
Nivel Superior                                        14
Plan Fines (Trayectos y Deudores)                      2
Psicología Comunitaria y Pedagogía Social (C.E.C)      2
Residencia Laboral,Pasantías, Artística                4
Name: establecimiento_id, dtype: int64

In [20]:
print("cantidad de NaN por columna")
df_establecimientos.isna().sum().sort_values(ascending=False)

cantidad de NaN por columna

rpv                       194
turnos                      6
email                       2
varones                     1
mujeres                     1
secciones                   1
direccion                   1
dependencia                 1
sector                      1
area                        1
telefono                    1
ambito                      1
desfavorabilidad            1
periodo                     1
cui                         1
sede_axo_ext                1
categoria                   1
subvencion                  1
tipo_organizacion           1
latitud                     1
longitud                    1
matricula                   1
cue                         1
anexo                       1
nro_escuela                 1
depend_func                 1
municipio_id                0
establecimiento_id          0
municipio_nombre            0
cueanexo                    0
clave                       0
nivel                       0
modalidad                   0
establecimiento_nombre      0
region_educativa            0
dtype: int64

In [21]:
df_la_plata = df_establecimientos[
    df_establecimientos["municipio_nombre"] == "La Plata"
].copy()

print("Registros:", len(df_la_plata))
print("Establecimientos:", df_la_plata["establecimiento_id"].nunique())

Registros: 337
Establecimientos: 290

In [22]:
df_establecimientos[
    (df_establecimientos["region_educativa"] == "Región 1") &
    (df_establecimientos["municipio_nombre"] != "La Plata")
][
    ["municipio_nombre", "establecimiento_id", "establecimiento_nombre", "nivel", "region_educativa"]
]

,municipio_nombre,establecimiento_id,establecimiento_nombre,nivel,region_educativa
222,Berisso,187,"ESCUELA DE EDUCACIÓN SECUNDARIA Nº 3 ""LOLA MORA""",Nivel Secundario,Región 1

En al Región Educativa 1 solo aparecen La Plata y Berisso. En éste último aparece solo la EES N° 3 "Lola Mora".

In [23]:
df_establecimientos.groupby("region_educativa")["municipio_nombre"].unique()

region_educativa
Región 1     [La Plata, Berisso]
Región 15              [Alberti]
Región 23        [Adolfo Alsina]
Región 4      [Florencio Varela]
Región 5       [Almirante Brown]
Name: municipio_nombre, dtype: object

Solamente me interesan las escuelas de La Plata

In [24]:
df_la_plata = df_establecimientos[
    df_establecimientos["municipio_nombre"] == "La Plata"
].copy()

print("Registros:", len(df_la_plata))
print("Establecimientos únicos:", df_la_plata["establecimiento_id"].nunique())

Registros: 337
Establecimientos únicos: 290

In [27]:
df_la_plata.info()

<class 'pandas.DataFrame'>
Index: 337 entries, 0 to 338
Data columns (total 35 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   municipio_id            337 non-null    int64
 1   municipio_nombre        337 non-null    str
 2   establecimiento_id      337 non-null    int64
 3   establecimiento_nombre  337 non-null    str
 4   region_educativa        337 non-null    str
 5   clave                   337 non-null    str
 6   cueanexo                337 non-null    int64
 7   modalidad               337 non-null    str
 8   nivel                   337 non-null    str
 9   direccion               337 non-null    str
 10  telefono                337 non-null    str
 11  rpv                     220 non-null    str
 12  email                   336 non-null    str
 13  sector                  337 non-null    str
 14  dependencia             337 non-null    str
 15  tipo_organizacion       337 non-null    str
 16  area                    337 non-null    str
 17  ambito                  337 non-null    str
 18  desfavorabilidad        337 non-null    float64
 19  subvencion              337 non-null    str
 20  sede_axo_ext            337 non-null    str
 21  categoria               337 non-null    str
 22  depend_func             337 non-null    str
 23  cui                     337 non-null    str
 24  periodo                 337 non-null    str
 25  matricula               337 non-null    float64
 26  varones                 337 non-null    float64
 27  mujeres                 337 non-null    float64
 28  secciones               337 non-null    float64
 29  turnos                  337 non-null    str
 30  cue                     337 non-null    float64
 31  anexo                   337 non-null    float64
 32  nro_escuela             337 non-null    float64
 33  latitud                 337 non-null    float64
 34  longitud                337 non-null    float64
dtypes: float64(10), int64(3), str(22)
memory usage: 94.8 KB

¿Cómo se distribuyen los establecimientos educativos de La Plata según nivel, modalidad y sector?

In [28]:
df_la_plata.groupby("nivel")["establecimiento_id"].nunique().sort_values(ascending=False)

nivel
Nivel Primario                             153
Nivel Inicial                               86
Nivel Secundario                            45
Formación Integral                          21
Nivel Superior                              12
Formación Profesional                        8
Ciclo de Iniciación                          3
Ciclo Medio                                  3
Residencia Laboral,Pasantías, Artística      2
Cursos y Talleres                            2
Educación Física (C.E.F.)                    1
Plan Fines (Trayectos y Deudores)            1
Name: establecimiento_id, dtype: int64

In [30]:
df_la_plata.groupby("modalidad")["establecimiento_id"].nunique().sort_values(ascending=False)

modalidad
Educación Común                   197
Educación de Jóvenes y Adultos     53
Educación Especial                 21
Educación Técnico Profesional      12
Educación Artística                 6
Educación Física                    1
Name: establecimiento_id, dtype: int64

In [31]:
df_la_plata.groupby("sector")["establecimiento_id"].nunique().sort_values(ascending=False)

sector
Estatal    290
Name: establecimiento_id, dtype: int64

In [32]:
df_la_plata.nunique().sort_values()

municipio_id                1
municipio_nombre            1
region_educativa            1
dependencia                 1
sector                      1
periodo                     1
subvencion                  1
area                        1
sede_axo_ext                2
ambito                      3
desfavorabilidad            4
anexo                       4
categoria                   4
modalidad                   6
depend_func                 9
nivel                      12
tipo_organizacion          21
turnos                     23
secciones                  53
rpv                       179
varones                   197
mujeres                   202
cui                       221
nro_escuela               240
telefono                  256
matricula                 268
cue                       270
email                     277
direccion                 280
establecimiento_nombre    290
clave                     290
establecimiento_id        290
cueanexo                  290
latitud                   290
longitud                  290
dtype: int64

In [33]:
columnas_categoricas = [
    "modalidad",
    "nivel",
    "sector",
    "dependencia",
    "desfavorabilidad",
    "anexo",
    "categoria",
    "depend_func",
    "tipo_organizacion"
]

for col in columnas_categoricas:
    print(f"\n--- {col} ---")
    print(df_la_plata[col].value_counts(dropna=False))

--- modalidad ---
modalidad
Educación Común                   197
Educación Especial                 61
Educación de Jóvenes y Adultos     54
Educación Artística                12
Educación Técnico Profesional      12
Educación Física                    1
Name: count, dtype: int64

--- nivel ---
nivel
Nivel Primario                             153
Nivel Inicial                               86
Nivel Secundario                            45
Formación Integral                          21
Nivel Superior                              12
Formación Profesional                        8
Ciclo Medio                                  3
Ciclo de Iniciación                          3
Cursos y Talleres                            2
Residencia Laboral,Pasantías, Artística      2
Educación Física (C.E.F.)                    1
Plan Fines (Trayectos y Deudores)            1
Name: count, dtype: int64

--- sector ---
sector
Estatal    337
Name: count, dtype: int64

--- dependencia ---
dependencia
Oficial    337
Name: count, dtype: int64

--- desfavorabilidad ---
desfavorabilidad
0.0    253
1.0     50
2.0     29
3.0      5
Name: count, dtype: int64

--- anexo ---
anexo
0.0    317
1.0      8
2.0      7
3.0      5
Name: count, dtype: int64

--- categoria ---
categoria
Primera    265
Segunda     42
S/Datos     25
Tercera      5
Name: count, dtype: int64

--- depend_func ---
depend_func
Dirección Provincial de Educación Primaria                      96
Dirección Provincial de Educación Inicial                       70
Dirección de Educación Especial                                 61
Dirección de Educación de Jóvenes, Adultos y Adultos Mayores    50
Dirección Provincial de Educación Secundaria                    25
Dirección Provincial de Educación Técnico Profesional           16
Dirección de Educación Artística                                12
Dirección Provincial de Educación Superior                       6
Dirección de Educación Física                                    1
Name: count, dtype: int64

--- tipo_organizacion ---
tipo_organizacion
ESCUELA DE EDUCACIÓN PRIMARIA                                         96
JARDÍN DE INFANTES                                                    68
ESCUELA DE EDUCACIÓN ESPECIAL                                         56
CENTRO DE EDUCACIÓN PRIMARIA DE ADULTOS                               25
ESCUELA DE EDUCACIÓN SECUNDARIA                                       24
ESCUELA DE EDUCACIÓN PRIMARIA DE ADULTOS                              14
CENTRO EDUCATIVO DE NIVEL SECUNDARIO (C.E.N.S.)                       10
ESCUELA DE EDUCACIÓN SECUNDARIA TÉCNICA                                9
INSTITUTO SUPERIOR DE FORMACIÓN DOCENTE Y TÉCNICA                      8
CENTRO DE FORMACIÓN INTEGRAL                                           5
CENTRO DE FORMACIÓN PROFESIONAL                                        4
ESCUELA DE DANZAS CLÁSICAS                                             3
CONSERVATORIO DE MÚSICA                                                3
ESCUELA DE TEATRO                                                      3
ESCUELA DE EDUCACIÓN ARTÍSTICA                                         2
JARDÍN MATERNAL                                                        2
ESCUELA DE DANZAS TRADICIONALES                                        1
CENTRO DE EDUCACIÓN FÍSICA                                             1
ESCUELA DE EDUCACIÓN SECUNDARIA AGRARIA                                1
ESCUELA DE EDUCACIÓN MEDIA                                             1
CENTRO ESPECIALIZADO PARA ADULTOS CON ORIENTACIÓN EN SALUD (CEBAS)     1
Name: count, dtype: int64

In [34]:
establecimientos_por_nivel = (
    df_la_plata
    .groupby("nivel")["establecimiento_id"]
    .nunique()
    .sort_values(ascending=False)
)

establecimientos_por_nivel

nivel
Nivel Primario                             153
Nivel Inicial                               86
Nivel Secundario                            45
Formación Integral                          21
Nivel Superior                              12
Formación Profesional                        8
Ciclo de Iniciación                          3
Ciclo Medio                                  3
Residencia Laboral,Pasantías, Artística      2
Cursos y Talleres                            2
Educación Física (C.E.F.)                    1
Plan Fines (Trayectos y Deudores)            1
Name: establecimiento_id, dtype: int64

In [35]:
establecimientos_por_modalidad = (
    df_la_plata
    .groupby("modalidad")["establecimiento_id"]
    .nunique()
    .sort_values(ascending=False)
)

establecimientos_por_modalidad

modalidad
Educación Común                   197
Educación de Jóvenes y Adultos     53
Educación Especial                 21
Educación Técnico Profesional      12
Educación Artística                 6
Educación Física                    1
Name: establecimiento_id, dtype: int64

¿Por qué tenemos 290 establecimientos únicos, pero la suma de establecimientos por nivel da 337?

La respuesta está en que un mismo establecimiento puede ofrecer varios niveles. Por ejemplo:
Establecimiento 71
Inicial
Primario
Formación Profesional
Formación Integral

In [36]:
# cuántos niveles ofrece cada establecimiento
niveles_por_establecimiento = (
    df_la_plata
    .groupby("establecimiento_id")["nivel"]
    .nunique()
)

niveles_por_establecimiento.value_counts().sort_index()

nivel
1    265
2      5
3     18
4      2
Name: count, dtype: int64

In [37]:
df_la_plata.groupby("establecimiento_id")["nivel"].agg(list).head(20)

establecimiento_id
1     [Nivel Superior, Ciclo Medio, Ciclo de Iniciac...
2                                   [Cursos y Talleres]
3                                   [Cursos y Talleres]
7     [Ciclo de Iniciación, Ciclo Medio, Nivel Super...
8     [Ciclo de Iniciación, Nivel Superior, Ciclo Me...
9                                      [Nivel Superior]
10                                     [Nivel Primario]
11                                     [Nivel Primario]
13                                     [Nivel Primario]
14                                     [Nivel Primario]
15                                     [Nivel Primario]
16                                     [Nivel Primario]
17                                     [Nivel Primario]
18                                     [Nivel Primario]
19                                     [Nivel Primario]
20                                     [Nivel Primario]
21                                     [Nivel Primario]
22                                     [Nivel Primario]
23                                     [Nivel Primario]
24                                     [Nivel Primario]
Name: nivel, dtype: object

¿Qué información cuantitativa tenemos de esos establecimientos?

Especialmente:

matricula
varones
mujeres
secciones

In [38]:
df_la_plata[
    ["matricula", "varones", "mujeres", "secciones"]
].describe()

         matricula      varones      mujeres   secciones
count   337.000000   337.000000   337.000000  337.000000
mean    314.329377   155.219585   159.109792   13.486647
std     377.012790   177.120215   232.780111   15.706780
min       1.000000     0.000000     0.000000    0.000000
25%      86.000000    42.000000    37.000000    4.000000
50%     175.000000    84.000000    86.000000   10.000000
75%     450.000000   233.000000   218.000000   19.000000
max    3488.000000  1296.000000  2393.000000  165.000000

La diferencia entre media (314) y mediana (175) es enorme.

Eso nos dice que probablemente tenemos una distribución muy sesgada hacia la derecha: unas pocas unidades educativas tienen matrículas muy grandes y empujan la media hacia arriba.

In [39]:
# ¿cuántos datos faltan?
df_la_plata[
    ["matricula", "varones", "mujeres", "secciones"]
].isna().sum()

matricula    0
varones      0
mujeres      0
secciones    0
dtype: int64

In [40]:
# creación de la columna de varones + mujeres
df_la_plata["suma_genero"] = (
    df_la_plata["varones"] + df_la_plata["mujeres"]
)

(df_la_plata["matricula"] == df_la_plata["suma_genero"]).value_counts()

True    337
Name: count, dtype: int64

In [41]:
df_la_plata["diferencia_matricula"] = (
    df_la_plata["matricula"] - df_la_plata["suma_genero"]
)

df_la_plata["diferencia_matricula"].value_counts().sort_index()

diferencia_matricula
0.0    337
Name: count, dtype: int64

¿cuánta matrícula hay realmente en el sistema educativo estatal registrado de La Plata?

In [42]:
# total matricula 
df_la_plata.groupby("nivel").agg(
    matricula=("matricula", "sum")
).sort_values("matricula", ascending=False).sum()

matricula    105929.0
dtype: float64

In [43]:
df_la_plata.groupby("nivel").agg(
    establecimientos=("establecimiento_id", "nunique"),
    secciones=("secciones", "sum"),
    matricula=("matricula", "sum")
).sort_values("matricula", ascending=False)

,establecimientos,secciones,matricula
nivel,,,
Nivel Primario,153,1891.0,46402.0
Nivel Secundario,45,1200.0,26943.0
Nivel Inicial,86,587.0,10388.0
Nivel Superior,12,285.0,9179.0
Educación Física (C.E.F.),1,165.0,3488.0
Formación Profesional,8,203.0,3455.0
Cursos y Talleres,2,121.0,2371.0
Formación Integral,21,0.0,1769.0
Ciclo Medio,3,40.0,929.0
Ciclo de Iniciación,3,33.0,664.0
Plan Fines (Trayectos y Deudores),1,20.0,300.0
"Residencia Laboral,Pasantías, Artística",2,0.0,41.0

In [44]:
df_la_plata[df_la_plata["secciones"] == 0][
    [
        "establecimiento_id",
        "establecimiento_nombre",
        "nivel",
        "modalidad",
        "matricula",
        "secciones"
    ]
]

,establecimiento_id,establecimiento_nombre,nivel,modalidad,matricula,secciones
52,54,"ESCUELA ESPECIAL Nº503 ""J. J. GORRITTI""",Formación Integral,Educación Especial,76.0,0.0
53,54,"ESCUELA ESPECIAL Nº503 ""J. J. GORRITTI""",Nivel Inicial,Educación Especial,10.0,0.0
54,54,"ESCUELA ESPECIAL Nº503 ""J. J. GORRITTI""",Nivel Primario,Educación Especial,161.0,0.0
55,56,"ESCUELA ESPECIAL Nº509 ""DR. CARLOS COMETTO""",Formación Integral,Educación Especial,40.0,0.0
56,56,"ESCUELA ESPECIAL Nº509 ""DR. CARLOS COMETTO""",Nivel Inicial,Educación Especial,35.0,0.0
...,...,...,...,...,...,...
108,75,"CENTRO DE FORMACIÓN INTEGRAL Nº 2 ""MAESTRO ISA...","Residencia Laboral,Pasantías, Artística",Educación Especial,27.0,0.0
109,75,"CENTRO DE FORMACIÓN INTEGRAL Nº 2 ""MAESTRO ISA...",Formación Integral,Educación Especial,98.0,0.0
110,75,"CENTRO DE FORMACIÓN INTEGRAL Nº 2 ""MAESTRO ISA...",Formación Profesional,Educación Especial,7.0,0.0
111,76,"CENTRO DE FORMACIÓN INTEGRAL Nº 3 ""RODOLFO J. ...",Formación Integral,Educación Especial,97.0,0.0
112,76,"CENTRO DE FORMACIÓN INTEGRAL Nº 3 ""RODOLFO J. ...",Formación Profesional,Educación Especial,51.0,0.0

In [45]:
pd.crosstab(
    df_la_plata["modalidad"],
    df_la_plata["secciones"] == 0
)

secciones                       False  True
modalidad
Educación Artística                12      0
Educación Común                   197      0
Educación Especial                  0     61
Educación Física                    1      0
Educación Técnico Profesional      12      0
Educación de Jóvenes y Adultos     54      0

Matrícula total por modalidad

¿Qué modalidades concentran mayor matrícula y qué niveles explican esa concentración?

In [46]:
matricula_modalidad = (
    df_la_plata
    .groupby("modalidad")
    .agg(
        establecimientos=("establecimiento_id", "nunique"),
        matricula=("matricula", "sum")
    )
    .sort_values("matricula", ascending=False)
)

matricula_modalidad

                                establecimientos  matricula
modalidad
Educación Común                              197    73027.0
Educación Técnico Profesional                 12    11622.0
Educación de Jóvenes y Adultos                53     8700.0
Educación Artística                            6     5209.0
Educación Especial                            21     3883.0
Educación Física                               1     3488.0

¿Cómo se distribuye la oferta educativa de La Plata entre modalidades y niveles?

In [59]:
matricula_modalidad_nivel = (
    df_la_plata
    .groupby(["nivel", "modalidad"])["matricula"]
    .sum()
    .sort_values(ascending=False)
    .reset_index()   # opcional, si querés modalidad/nivel como columnas
)

matricula_modalidad_nivel

,nivel,modalidad,matricula
0,Nivel Primario,Educación Común,41601.0
1,Nivel Secundario,Educación Común,16684.0
2,Nivel Inicial,Educación Común,10176.0
3,Nivel Secundario,Educación Técnico Profesional,8254.0
4,Nivel Superior,Educación Común,4566.0
5,Educación Física (C.E.F.),Educación Física,3488.0
6,Nivel Superior,Educación Técnico Profesional,3368.0
7,Formación Profesional,Educación de Jóvenes y Adultos,3359.0
8,Nivel Primario,Educación de Jóvenes y Adultos,3036.0
9,Cursos y Talleres,Educación Artística,2371.0
10,Nivel Secundario,Educación de Jóvenes y Adultos,2005.0
11,Formación Integral,Educación Especial,1769.0
12,Nivel Primario,Educación Especial,1765.0
13,Nivel Superior,Educación Artística,1245.0
14,Ciclo Medio,Educación Artística,929.0
15,Ciclo de Iniciación,Educación Artística,664.0
16,Plan Fines (Trayectos y Deudores),Educación de Jóvenes y Adultos,300.0
17,Nivel Inicial,Educación Especial,212.0
18,Formación Profesional,Educación Especial,96.0
19,"Residencia Laboral,Pasantías, Artística",Educación Especial,41.0

In [60]:
# ¿Hay duplicados exactos?
df_la_plata.duplicated().sum()

np.int64(0)

In [63]:
# Reviso si faltan coordenadas, dado que quiero eventualmente hacer análisis territorial
df_la_plata[["latitud", "longitud"]].isna().sum()

latitud     0
longitud    0
dtype: int64

In [67]:
df_la_plata[
    ["matricula", "varones", "mujeres", "secciones"]
].isna().sum()

matricula    0
varones      0
mujeres      0
secciones    0
dtype: int64

In [68]:
resumen_calidad = pd.DataFrame({
    "filas": [len(df_la_plata)],
    "establecimientos_unicos": [
        df_la_plata["establecimiento_id"].nunique()
    ],
    "duplicados_exactos": [
        df_la_plata.duplicated().sum()
    ],
    "duplicados_establecimiento_nivel": [
        df_la_plata.duplicated(
            subset=["establecimiento_id", "nivel"]
        ).sum()
    ],
    "filas_con_latitud_faltante": [
        df_la_plata["latitud"].isna().sum()
    ],
    "filas_con_longitud_faltante": [
        df_la_plata["longitud"].isna().sum()
    ]
})

resumen_calidad

,filas,establecimientos_unicos,duplicados_exactos,duplicados_establecimiento_nivel,filas_con_latitud_faltante,filas_con_longitud_faltante
0,337,290,0,0,0,0

Filas del archivo original: 490; Columnas: 35.

Filas de La Plata: 337; Establecimientos únicos en La Plata: 290.

Las 337 filas de La Plata representan registros de establecimientos asociados a niveles o servicios educativos, no 337 escuelas necesariamente distintas. En ese recorte aparecen 290 valores únicos de establecimiento_id.
No se detectaron duplicados exactos ni duplicados de la clave establecimiento_id + nivel en las 337 filas. Tampoco faltaban coordenadas en ese recorte.